apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: keystone-app-hpa
  namespace: default
spec:
  minReplicas: 4
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keystone-app
  targetCPUUtilizationPercentage: 10
