apiVersion: v1
kind: Service
metadata:
 name: mariadb-service
 labels:
  app: mariadb
spec:
 type: LoadBalancer
 clusterIP: 10.105.16.121
 ports:
  - name: default
    port: 3306
    targetPort: 3306
    protocol: TCP
 selector:
  app: mariadb

