apiVersion: v1
kind: Service
metadata:
 name: keystone-service-1
 labels:
  app: keystone
spec:
 type: LoadBalancer
 clusterIP: 10.105.197.94
 selector:
  app: keystone
 ports:
  - name: default
    port: 13068
    targetPort: 5000
    protocol: TCP
 selector:
  app: keystone
