apiVersion: v1
kind: Service
metadata:
 name: keystone-service-2
 labels:
  app: keystone
spec:
 type: LoadBalancer
 clusterIP: 10.105.197.51
 selector:
  app: keystone
 ports:
  - name: default
    port: 9694
    targetPort: 5000
    protocol: TCP
 selector:
  app: keystone
