apiVersion: v1
kind: Service
metadata:
 name: keystone-service-3
 labels:
  app: keystone
spec:
 type: LoadBalancer
 clusterIP: 10.105.197.44
 selector:
  app: keystone
 ports:
  - name: default
    port: 63621
    targetPort: 5000
    protocol: TCP
 selector:
  app: keystone
