apiVersion: v1
kind: Service
metadata:
 name: keystone-service-4
 labels:
  app: keystone
spec:
 type: LoadBalancer
 clusterIP: 10.105.197.56
 selector:
  app: keystone
 ports:
  - name: default
    port: 16012
    targetPort: 5000
    protocol: TCP
 selector:
  app: keystone
