apiVersion: v1
kind: Service
metadata:
 name: keystone-service-5
 labels:
  app: keystone
spec:
 type: LoadBalancer
 clusterIP: 10.105.197.67
 selector:
  app: keystone
 ports:
  - name: default
    port: 61282
    targetPort: 5000
    protocol: TCP
 selector:
  app: keystone
