apiVersion: v1
kind: Service
metadata:
 name: decoy-mariadb-service
 labels:
  app: decoy-mariadb
spec:
 type: LoadBalancer
 clusterIP: 10.105.16.120
 ports:
  - name: default
    port: 3306
    targetPort: 3306
    protocol: TCP
 selector:
  app: decoy-mariadb

