apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: keystone-app-hpa
  namespace: default
spec:
  maxReplicas: 16 
  minReplicas: 8 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keystone-app
  targetCPUUtilizationPercentage: 80

