apiVersion: v1
kind: Service
metadata:
 name: keystone-service
 labels:
  app: keystone
spec:
 type: LoadBalancer
 clusterIP: 10.105.197.25
 ports:
  - name: default
    port: 5000
    targetPort: 5000
    protocol: TCP
  - name: admin
    port: 35357
    targetPort: 35357
    protocol: TCP
 selector:
  app: keystone

