apiVersion: apps/v1
kind: Deployment
metadata:
 name: decoy-keystone-app
spec:
 replicas: 1
 selector:
  matchLabels:
   app: decoy-keystone
 template:
  metadata:
   labels:
    app: decoy-keystone
  spec:
   containers:
   - name: decoy-keystone
     image: obedmr/keystone
     securityContext:
       privileged: true
     env:
     - name: DATABASE_HOST
       value: 10.105.16.120:3306
     - name: KEYSTONE_DB_USER
       value: keystone
     - name: KEYSTONE_DB_PASSWORD
       value: secret
     - name: KEYSTONE_DB_NAME
       value: keystone
     resources:
       requests:
          cpu: "300m"
       limits:
          cpu: "300m"
