apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-galera-ss-0
  labels:
    app: galera-ss
    podindex: "0"
spec:
#  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    server: 172.21.2.123
    path: /data/pods/galera-0/datadir
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-galera-ss-1
  labels:
    app: galera-ss
    podindex: "1"
spec:
#  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    server: 172.21.2.123
    path: /data/pods/galera-1/datadir
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-galera-ss-2
  labels:
    app: galera-ss
    podindex: "2"
spec:
#  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    server: 172.21.2.123
    path: /data/pods/galera-2/datadir
